---
title: "git_00"
author: "Gaby Mancera"
date: "Year 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
’Twas brillig, and the slithy toves   
      Did gyre and gimble in the wabe:   
All mimsy were the borogoves,   
      And the mome raths outgrabe.   

“Beware the Jabberwock, my son!   

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
My long two-pointed ladder's sticking through a tree   
Toward heaven still,   
And there's a barrel that I didn't fill   
Beside it, and there may be two or three   
Apples I didn't pick upon some bough.  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
I wandered lonely as a cloud.  
That floats on high o'er vales and hills,  
When all at once I saw a crowd,  
A host, of golden daffodils;  
Beside the lake, beneath the trees,  
Fluttering and dancing in the breeze.  

Continuous as the stars that shine  
And twinkle on the milky way,  
They stretched in never-ending line  
Along the margin of a bay:  
Ten thousand saw I at a glance,  
Tossing their heads in sprightly dance.  

The waves beside them danced; but they  
Out-did the sparkling waves in glee:  
A poet could not but be gay,  
In such a jocund company:  
I gazed—and gazed—but little thought  
What wealth the show to me had brought:  
